---
- name: Deploy app in new namespace
  hosts: localhost
  tasks:
    - name: Create a k8s namespace
      kubernetes.core.k8s:
        name: my-app
        api_version: v1
        kind: Namespace
        state: present
    - name: Deploy nginx
      kubernetes.core.k8s:
        src: ~/code/terraform-eks/nginx-config.yml
        state: present
        namespace: my-app
